# Generated by Django 5.1.5 on 2025-02-16 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0003_alter_card_deck_alter_deck_author_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercard',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_cards', to='decks.card'),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='difficulty',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='due',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='last_review',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='stability',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Learning'), (2, 'Review'), (3, 'Relearning')], null=True),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='step',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userdeck',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_decks', to='decks.deck'),
        ),
        migrations.AlterField(
            model_name='userdeck',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_decks', to=settings.AUTH_USER_MODEL),
        ),
    ]
